name: BEAR.Sunday
safe: true
lsi: false

url: http://bearsunday.github.io
title: BEAR.Sunday

markdown: kramdown
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: pygments
