version: "3"
services:
  app:
    container_name: jekyllbearsunday
    build:
      context: .
      dockerfile: Dockerfile
    command: jekyll serve
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
