name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rbenv ruby-build build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Setup Ruby
        run: |
          eval "$(rbenv init - bash)"
          rbenv install 3.2.2 -s
          rbenv global 3.2.2
          ruby -v
        shell: bash

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
